//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Mgmt.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book_Detail
    {
        public int Id { get; set; }
        public string Book_Name { get; set; }
        public string Author_Name { get; set; }
        public string Publication_Name { get; set; }
        public Nullable<System.DateTime> Purchase_Date { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Quentity { get; set; }
    }
}
