//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Mgmt.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Detail
    {
        public int Id { get; set; }
        public string Student_Name { get; set; }
        public string Enrollment { get; set; }
        public string Department { get; set; }
        public string Semester { get; set; }
        public string Contact_No { get; set; }
        public string Email_Id { get; set; }
        public string Image_link { get; set; }
    }
}
