//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Mgmt.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Detail
    {
        public int id { get; set; }
        public string user_name { get; set; }
        public string password { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string contact_no { get; set; }
        public string image_link { get; set; }
        public string gmail { get; set; }
    }
}
